name: test

on:

  push:
    branches:
      - '*'

  pull_request:
    branches:
      - 'master'

jobs:

  Phase-1:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: echo
        run: echo "Hello World!"

      - name: ls
        run: ls -al